[build]
  publish = "frontend/dist"
  command = "echo 'No build needed - serving pre-built files'"

[[redirects]]
  from = "/api/*"
  to = "https://fisd-counselor.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
