services:
  - type: web
    name: fisd-counselor-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/health

  - type: web
    name: fisd-counselor-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://fisd-counselor-backend.onrender.com
